var Sakralne_pam = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      id: 40,
      geometry: {
        type: "Point",
        coordinates: [19.401576, 48.547846],
      },
      properties: {
        FID: 40,
        Nazov: "Kláštor Detva",
        Lokalita: "Jána Pavla II 3168, 962 12 Detva",
        TYP: "Sakralne_pam",
        Vznik: 2007,
        PICURL: "klastor.jpg",
        PICURL1: "klastor1.jpg",
        PICURL2: "klastor2.jpg",
        Text_k:
          "Najnovším sakrálnym objektom v Detve je Kláštor Božieho milosrdenstva         a Kráľovnej Karmelu. ",
        Text: "Bol postavený na Krpeľnom vŕšku, ktorý sa týči nad sídliskom. V r. 1844 tu boli postavené šibenice, na ktorých údajne popravili dvoch odsúdencov.",
        Text1:
          "Najnovším sakrálnym objektom v Detve je Kláštor Božieho milosrdenstva         a Kráľovnej Karmelu. Bol postavený na Krpeľnom vŕšku, ktorý sa týči nad sídliskom. V r. 1844 tu boli postavené šibenice, na ktorých údajne popravili dvoch odsúdencov.   Kláštor je jednoducho zariadený, s prísnou klauzúrou. Jeho súčasťou je záhrada a hrobka. Kaplnka je z neklauzurovanej strany prístupná pre verejnosť. Svätú omšu, na ktorej sú oddelene prítomní veriaci i rehoľné sestry, sem chodia denne slúžiť detvianski kňazi. Prvý kláštor bosých karmelitánok na Slovensku bol založený v júni 1995 v Košiciach. Keď v ňom počet sestier prekročil hranicu 21, stanovenú konštitúciami, aby mohli byť prijímané ďalšie kandidátky, začalo sa pripravovať založenie ďalšieho kláštora. 28. júla 2007 banskobystrický biskup Rudolf Baláž slávnostne posvätil kaplnku a kláštor Božieho milosrdenstva a Kráľovnej Karmelu v Detve. Z Košíc prišlo do nového kláštora 11 sestier. Žijú podľa reformy, ktorú v Karmelitánskom ráde v 16. storočí uskutočnili dvaja veľkí španielski mystici - sv. Terézia od Ježiša (z Avily) a sv. Ján z  Kríža. Bol to návrat k prvotnej charizme: k ideálu pustovníckeho života, mlčaniu, úplnému zdržiavaniu sa mäsa, skrytému životu v klauzúre, pravidelnej vnútornej modlitbe a  modlitbe v chóre, ako aj k prvkom komunitného života. Takýmto spôsobom života sa i dnes usilujú žiť bosé karmelitánky v Detve. Svoj čas venujú svätej omši, modlitbe, ale i práci v dielňach, v domácnosti a v záhrade. Ich spoločníkom počas dňa je samota a mlčanie. Na spoločnú rekreáciu, keď sa sestry môžu spontánne a srdečne porozprávať majú vyhradený čas po obede a po večeri.",
        Zdroj:
          "Fotografie: https://www.detva.sk/klastor-bozieho-milosrdenstva-a-kralovnej-karmelu.html?idpgall=492019, https://www.podpolanie.sk/sk/place/174?section=gallery; Text: Bartková Anna, <i> Dejiny farnosti Detva <i>, Diplomová práca, 2008",
        Google_map:
          "https://www.google.com/maps/place/Kl%C3%A1%C5%A1tor+Detva/@48.5478338,19.3989982,17z/data=!3m1!4b1!4m6!3m5!1s0x47155ab5e179cc21:0x5611652e1f1c3c69!8m2!3d48.5478303!4d19.4015731!16s%2Fg%2F11g6yns1rt?entry=ttu&g_ep=EgoyMDI1MDkxMC4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: 19.401576,
        SIRKA: 48.547846,
        Parcela: "4464/10",
        Tel_cislo: "045/29 015 01",
        Mail: "sestrydetva.bosikarmelitani.sk, karmel.detva@gmail.com",
        Stranka:
          "https://faradetva.sk/o-nas/sakralne-objekty/klastorny-kostol-karmel",
      },
    },
    {
      type: "Feature",
      id: 41,
      geometry: {
        type: "Point",
        coordinates: [19.425027, 48.565202],
      },
      properties: {
        FID: 41,
        Nazov: "Expozícia drevených vyrezávaných krížov (kalvária)",
        Lokalita: "Cintorínska 1425/46, 962 12 Detva",
        TYP: "Sakralne_pam",
        Vznik: 0,
        PICURL: "kalvaria_krize.jpg",
        PICURL1: "kalvaria_krize1.jpg",
        PICURL2: "kalvaria_krize2.jpg",
        Text_k:
          "Detvianske vyrezávané drevené kríže sa stali súčasťou národného kultúrneho dedičstva Slovenska.",
        Text: " ",
        Text1:
          "Detvianske vyrezávané drevené kríže sa stali súčasťou národného kultúrneho dedičstva Slovenska. Geometrické a rastlinné ornamenty spolu s kresťanskou symbolikou zdobia prednú a bočné časti kríža. Prevažne sa vyrábajú z dubového dreva a jednotlivé ornamenty sa kolorujú. Najčastejšími ornamentami sú trojlist, kvietok, rozeta s kruhom, vinič so strapcom hrozna, svietnik, slimák, prstenec, sviatosť oltárna. Základná farba je tmavá a ornamenty sú biele, žlté, zelené, červené alebo belasé. Detvianske drevené kríže sú definované ako ľudové rezbárske práce s plochou alebo plastickou rezbou s geometrickým a rastlinným ornamentom. Dnes sa pôvodné kríže obnovujú, ale vyrábajú sa aj nové. Sú to najmä náhrobné ale aj prícestné kríže, ktoré stoja na rôznych miestach v Podpoľaní. Jedná sa prevažne o ručnú prácu zameranú na výrobu samotného kríža, ako aj rozkreslenie, vysekanie a maľovanie ornamentov. Viac ako 70 Detvianskych krížov je umiestnených na symbolickom cintoríne pri Popradskom plese. Na pamiatku obetiam Vysokých Tatier sú tam umiestňované pamätné tabule s menami, ale nikto tam nie je pochovaný. ",
        Zdroj:
          "Fotografie: Tomáš Belko; Text: https://www.podpolanie.sk/sk/place/372",
        Google_map:
          "https://www.google.com/maps/@48.5650602,19.4251917,17.25z?entry=ttu&g_ep=EgoyMDI1MDkyNC4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: 19.424132,
        SIRKA: 48.565446,
        Parcela: "97/1",
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
    {
      type: "Feature",
      id: 42,
      geometry: {
        type: "Point",
        coordinates: [19.424307, 48.565373],
      },
      properties: {
        FID: 42,
        Nazov: "Kalvária Detva",
        Lokalita: "Cintorínska ulica, 962 12 Detva",
        TYP: "Sakralne_pam",
        Vznik: 0,
        PICURL: "kalvaria_detva.jpg",
        PICURL1: "kalvaria_detva1.jpg",
        PICURL2: "kalvaria_detva2.jpg",
        Text_k:
          "Po Veľkej noci v r. 1910 sa začalo so stavbou Kalvárie na mieste, kde pôvodne stáli tri kríže a ľud to už Kalváriou aj nazýval.",
        Text: " Zásluhou šikovných murárov a tesárov zo Seliec bola od apríla do septembra aj hotová. Skaly ",
        Text1:
          "Po Veľkej noci v roku 1910 sa začalo so stavbou Kalvárie na mieste, kde pôvodne stáli tri kríže, pričom stavba bola vďaka murárom a tesárom zo Seliec dokončená už v septembri toho istého roku. Kalváriu tvorí 14 zastavení krížovej cesty a maličký kostolík, pričom zastavenia sú murované kaplnky s presklenými nikami, v ktorých sa nachádzajú polychrómované štukové reliéfy výjavov Krížovej cesty. Päť zastavení stojí po ľavej strane chodníka cez cintorín a ostatné pokračujú serpentínovito zalesneným kopcom až na jeho vrchol. Na vrchole kopca stojí kaplnka postavená v historizujúcom slohu s obdĺžnikovým pôdorysom, polygonálnym uzáverom, štukovou sochou Piety a vitrážovými oknami. Kalvária bola renovovaná v roku 1965 a posledná úprava prebehla v roku 2007, pričom svätá omša sa tu opäť slúži od roku 1991 vždy v septembri na sviatok Povýšenia sv. Kríža.",
        Zdroj:
          "Fotografie: Turisticko-informačná kancelária Detva, Samuel Vilhan; Text: Bartková Anna, <i> Dejiny farnosti Detva <i>, Diplomová práca, 2008",
        Google_map:
          "https://www.google.com/maps/place/Detvianska+kalv%C3%A1ria+(p%C3%BAtnick%C3%A9+miesto)/@48.5653151,19.4217284,17z/data=!3m1!4b1!4m6!3m5!1s0x47155ad80b4bbb65:0x9fcf67bc412a8585!8m2!3d48.5653116!4d19.4243033!16s%2Fg%2F11c2p__859?entry=ttu&g_ep=EgoyMDI1MDkx",
        DLZKA: 19.424307,
        SIRKA: 48.565373,
        Parcela: 96,
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
    {
      type: "Feature",
      id: 43,
      geometry: {
        type: "Point",
        coordinates: [19.418363, 48.559571],
      },
      properties: {
        FID: 43,
        Nazov: "Socha sv. Jána Nepomuckého",
        Lokalita: "Partizánska ulica pod kostolom",
        TYP: "Sakralne_pam",
        Vznik: 1768,
        PICURL: "nepomucky.jpg",
        PICURL1: "nepomucky1.jpg",
        PICURL2: "nepomucky2.jpg",
        Text_k:
          "V Detve sa do dnešných čias zachovala kamenná polychrómovaná socha sv. Jána Nepomuckého z roku 1768, ktorá stojí pred chudobiencom. ",
        Text: "Ján Nepomucký sa narodil okolo roku 1345 v Pomukoch, stal sa kňazom, neskôr pražským arcibiskupským vikárom, zomrel 20. marca 1393 v Prahe mučeníckou smrťou. ",
        Text1:
          "V Detve sa do dnešných čias zachovala kamenná polychrómovaná socha sv. Jána Nepomuckého z roku 1768, ktorá stojí pred chudobiencom. Ján Nepomucký sa narodil okolo roku 1345 v Pomukoch, stal sa kňazom, neskôr pražským arcibiskupským vikárom, zomrel 20. marca 1393 v Prahe mučeníckou smrťou. Po najobľúbenejšom kulte Panny Márie sa počas baroka veľmi rýchlo z Českého kráľovstva rozšíril po celej Habsburskej ríši i kult sv. Jána Nepomuckého. Na Slovensku sa stal tento český svätec veľmi rýchlo obľúbený. S počtom 170 výskytov sa patrocínium sv. Jána Nepomuckého nachádza na šiestom mieste v poradí zachovaných patrocínií na Slovensku.",
        Zdroj:
          "Fotografie:  Samuel Vilhan; Text: Bartková Anna, <i> Dejiny farnosti Detva <i>, Diplomová práca, 2008",
        Google_map:
          "https://www.google.com/maps/place/48%C2%B033'34.5%22N+19%C2%B025'06.1%22E/@48.5595719,19.4177193,19z/data=!3m1!4b1!4m4!3m3!8m2!3d48.559571!4d19.418363?entry=ttu&g_ep=EgoyMDI1MDkxMC4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: 19.418363,
        SIRKA: 48.559571,
        Parcela: "1397/1",
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
    {
      type: "Feature",
      id: 44,
      geometry: {
        type: "Point",
        coordinates: [19.420966, 48.563943],
      },
      properties: {
        FID: 44,
        Nazov: "Socha sv. Floriána",
        Lokalita: "Partizánska ulica pod cintorínom, 962 12 Detva",
        TYP: "Sakralne_pam",
        Vznik: 0,
        PICURL: "florian.jpg",
        PICURL1: "florian1.jpg",
        PICURL2: "florian2.jpg",
        Text_k: " ",
        Text: "V Detve stojí zachovaná prícestná socha sv. Floriána, ktorú detviansky ľud familiárne nazýva „Florianko“, čo deti skomolia a ešte i dnes povedia: „pri Froliankovi je odbočka na cintorín“. ",
        Text1:
          "V Detve stojí zachovaná prícestná socha sv. Floriána, ktorú detviansky ľud familiárne nazýva „Florianko“. Ide o neskorobarokovú kamennú, polychrómovanú sochu z 18. storočia, renovovanú v roku 1823 a 1850. Svätý Florián je ochrancom proti nebezpečenstvu ohňa a vody, proti suchu, neúrode a búrke a je patrónom hasičov. Detva bola postihovaná častými požiarmi, preto ľud chcel mať v meste práve sochu sv. Floriána ako ochrancu pred ohňom. Patrocínium sv. Floriána sa počas baroka viazalo na malé objekty umiestnené vo voľnej prírode alebo pri cestách a tieto sakrálne pamiatky komunikujú svoju dobu a historický význam pre miestnu komunitu.",
        Zdroj:
          "Fotografie: Samuel Vilhan, Turisticko-informačná kancelária Detva; Text: Bartková Anna, <i> Dejiny farnosti Detva <i>, Diplomová práca, 2008",
        Google_map:
          "https://www.google.com/maps/place/Socha+sv.Flori%C3%A1n/@48.5639341,19.4209426,20.5z/data=!4m6!3m5!1s0x47155b0003766741:0x57691bc322dbd97f!8m2!3d48.5639351!4d19.4209696!16s%2Fg%2F11ltfvkchq?entry=ttu&g_ep=EgoyMDI1MDkxMC4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: 19.420966,
        SIRKA: 48.563943,
        Parcela: 1554,
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
    {
      type: "Feature",
      id: 47,
      geometry: {
        type: "Point",
        coordinates: [19.389208, 48.537813],
      },
      properties: {
        FID: 47,
        Nazov: "Kaplnka Panny Márie , Matky ustavičnej pomoci - Krné",
        Lokalita: "Krné, 962 12 Detva",
        TYP: "Sakralne_pam",
        Vznik: 2008,
        PICURL: "kaplnka_krne.jpg",
        PICURL1: "kaplnka_krne1.jpg",
        PICURL2: "kaplnka_krne2.jpg",
        Text_k:
          "Koncom apríla 2007 bol dekanom Ľubošom Sabolom požehnaný pozemok v Krnom, na stavbu novej kaplnky vo farnosti.",
        Text: "V priebehu jedného roka si obyvatelia Krného pod vedením pána Jozefa Krnáča svojpomocne postavili Kaplnku Panny Márie, Matky ustavičnej pomoci.",
        Text1:
          "Koncom apríla 2007 bol dekanom Ľubošom Sabolom požehnaný pozemok v Krnom, na stavbu novej kaplnky vo farnosti. V priebehu jedného roka si obyvatelia Krného pod vedením pána Jozefa Krnáča svojpomocne postavili Kaplnku Panny Márie, Matky ustavičnej pomoci. Slávnostné požehnanie kaplnky dekanom Sabolom sa uskutočnilo 27. júla 2008. Každoročne býva pri kaplnke slávená výročná svätá omša, v poslednú júnovú alebo prvú júlovú nedeľu. Ikona Matky ustavičnej pomoci patrí dnes k známym obrazom Panny Márie. Pápež Pius IX. zveril obraz Matky ustavičnej pomoci v roku 1866 redemptoristom. Táto ikona vznikla na Kréte v 15. storočí a 300 rokov bola uctievaná v rímskom Kostole sv. Matúša. Od 26. apríla 1866 sa nachádza v Kostole sv. Alfonza v Ríme. Mariánska úcta sa vďaka redemptoristom upevňovala aj úctou k Matke ustavičnej pomoci, ktorá sa rozšírila takmer po celom svete. Kaplnka Panny Márie, Matky ustavičnej pomoci – Krné, r. 2022Kaplnka Panny Márie, Matky ustavičnej pomoci – Krné, r. 2022 Na Slovensko sa táto úcta dostala prostredníctvom českých redemptoristov po roku 1921, keď sa usadili v Podolínci a v Kostolnej-Záriečí. Ikona Matky ustavičnej pomoci sa nachádza vo všetkých rehoľných kostoloch redemptoristov. S touto úctou je spojená aj tzv. ustavičná novéna, ktorú sa veriaci modlia v stredu alebo v sobotu. Počas novény odznievajú poďakovania a prosby, ktoré ľudia Matke ustavičnej pomoci napíšu. Redemptoristi vedú k tejto úcte, pretože Panna Mária nám chce ustavične a účinne pomáhať. Napriek tomu, že Mária je najväčšou postavou obrazu, nie je jeho centrom. V geometrickom strede ikony sa stretajú ruky Márie a Ježiša. Ježišove malé ruky, ktorými sa drží pravej ruky Matky, symbolizujú hlavné posolstvo ikony: Ježiš aj v nebi vkladá do rúk Márie všetky milosti, aby nám ich rozdeľovala. Redemptoristi na celom svete slávia sviatok Panny Márie, Matky ustavičnej pomoci, 27. júna.",
        Zdroj:
          "Fotografie: Turisticko-informačná kancelária Detva; Text: https://faradetva.sk/o-nas/sakralne-objekty/kaplnky",
        Google_map:
          "https://www.google.com/maps/place/Krn%C3%A9+151,+962+12+Detva/@48.53777,19.38938,19z/data=!4m6!3m5!1s0x47155aacdfa99be3:0xef2d2bebb667b43f!8m2!3d48.5378012!4d19.3892126!16s%2Fg%2F11vwhcrhf6?entry=ttu&g_ep=EgoyMDI1MDkyNC4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: 19.389208,
        SIRKA: 48.537813,
        Parcela: "7933/7",
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
    {
      type: "Feature",
      id: 50,
      geometry: {
        type: "Point",
        coordinates: [19.420354, 48.5656],
      },
      properties: {
        FID: 50,
        Nazov: "Božia muka, Detva, Sládkovičová ulica",
        Lokalita: "Sládkovičová ulica",
        TYP: "Sakralne_pam",
        Vznik: 0,
        PICURL: "muky_sladkovicova.jpg",
        PICURL1: "muky_sladkovicova1.jpg",
        PICURL2: "muky_sladkovicova2.jpg",
        Text_k: " ",
        Text: " ",
        Text1: " ",
        Zdroj:
          "Fotografie: Samuel Vilhan, Turisticko-informačná kancelária Detva; Text: ",
        Google_map:
          "https://www.google.com/maps/@48.5656791,19.4202709,19.5z?entry=ttu&g_ep=EgoyMDI1MDkyNC4wIKXMDSoASAFQAw%3D%3D",
        GPS: "48.565607, 19.420354",
        DLZKA: 19.420354,
        SIRKA: 48.565607,
        Parcela: 316,
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
    {
      type: "Feature",
      id: 51,
      geometry: {
        type: "Point",
        coordinates: [19.418415, 48.553659],
      },
      properties: {
        FID: 51,
        Nazov: "Božia muka, Detva, ulica Jána Bottu",
        Lokalita: "ul. Jána Bottu",
        TYP: "Sakralne_pam",
        Vznik: 0,
        PICURL: "muky_bottu.jpg",
        PICURL1: "muky_bottu1.jpg",
        Text_k: " ",
        Text: " ",
        Text1: " ",
        Zdroj:
          "Fotografie: Samuel Vilhan, Turisticko-informačná kancelária Detva; Text: ",
        Google_map:
          "https://www.google.com/maps/place/48%C2%B033'13.2%22N+19%C2%B025'06.3%22E/@48.5536878,19.4183199,18.25z/data=!4m4!3m3!8m2!3d48.553659!4d19.418426?entry=ttu&g_ep=EgoyMDI1MDkyNC4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: 19.418415,
        SIRKA: 48.553659,
        Parcela: "3017/10",
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
    {
      type: "Feature",
      id: 55,
      geometry: {
        type: "Point",
        coordinates: [19.407786, 48.544058],
      },
      properties: {
        FID: 55,
        Nazov: "Božia muka, Detva - sídlisko, ul. Jánošíkova",
        Lokalita: "Jánošíkova 4, 962 12 Detva",
        TYP: "Sakralne_pam",
        Vznik: 0,
        PICURL: "muky_sidlisko.jpg",
        PICURL1: "muky_sidlisko1.jpg",
        PICURL2: "muky_sidlisko2.jpg",
        Text_k: " ",
        Text: " ",
        Text1: " ",
        Zdroj:
          "Fotografie: Samuel Vilhan, Turisticko-informačná kancelária Detva; Text: ",
        Google_map:
          "https://www.google.com/maps/place/48%C2%B032'38.6%22N+19%C2%B024'28.0%22E/@48.5440749,19.4072844,19z/data=!4m4!3m3!8m2!3d48.5440556!4d19.4077778?entry=ttu&g_ep=EgoyMDI1MTAxNC4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: 19.407786,
        SIRKA: 48.544058,
        Parcela: "4586/126",
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
    {
      type: "Feature",
      id: 56,
      geometry: {
        type: "Point",
        coordinates: [19.412276, 48.508949],
      },
      properties: {
        FID: 56,
        Nazov: "Božia muka, Detva, Piešť I",
        Lokalita: "Piešt 1",
        TYP: "Sakralne_pam",
        Vznik: 0,
        PICURL: "muky_piestI.jpg",
        PICURL1: "muky_piestI1.jpg",
        PICURL2: "muky_piestI2.jpg",
        Text_k: " ",
        Text: " ",
        Text1: " ",
        Zdroj:
          "Fotografie: Samuel Vilhan, Turisticko-informačná kancelária Detva; Text: ",
        Google_map:
          "https://www.google.com/maps/place/48%C2%B030'32.2%22N+19%C2%B024'44.2%22E/@48.5090858,19.411565,17.23z/data=!4m4!3m3!8m2!3d48.5089495!4d19.4122764?entry=ttu&g_ep=EgoyMDI1MTExMS4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: "19.412276",
        SIRKA: "48.508949",
        Parcela: "3017/10",
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
    {
      type: "Feature",
      id: 57,
      geometry: {
        type: "Point",
        coordinates: [19.405909, 48.502647],
      },
      properties: {
        FID: 57,
        Nazov: "Kaplnka Sedembolestnej Panny Márie - Piešť I. u Slobodov",
        Lokalita: "Piešt 1 u Slobodov, 962 12 Detva",
        TYP: "Sakralne_pam",
        Vznik: 0,
        PICURL: "kaplnka_piest_uslobodov.jpg",
        PICURL1: "kaplnka_piest_uslobodov1.jpg",
        PICURL2: "kaplnka_piest_uslobodov2.jpg",
        Text_k: " ",
        Text: " ",
        Text1: " ",
        Zdroj:
          "Fotografie: Turisticko-informačná kancelária Detva, Samuel Vilhan",
        Google_map:
          "https://www.google.com/maps/place/48%C2%B030'09.5%22N+19%C2%B024'21.3%22E/@48.5026505,19.4033341,17z/data=!3m1!4b1!4m4!3m3!8m2!3d48.502647!4d19.405909?entry=ttu&g_ep=EgoyMDI1MTEzMC4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: "19.405909",
        SIRKA: "48.502647",
        Parcela: "16911",
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
    {
      type: "Feature",
      id: 58,
      geometry: {
        type: "Point",
        coordinates: [19.405899, 48.508991],
      },
      properties: {
        FID: 58,
        Nazov: "Kaplnka Božieho milosrdenstva - Piešť I. u Svoreňov",
        Lokalita: "Piešť 1 u Svoreňov, 962 12 Detva",
        TYP: "Sakralne_pam",
        Vznik: 0,
        PICURL: "kaplnka_piest_usvorenov.jpg",
        PICURL1: "kaplnka_piest_usvorenov1.jpg",
        PICURL2: "kaplnka_piest_usvorenov2.jpg",
        Text_k: " ",
        Text: " ",
        Text1: " ",
        Zdroj: "Fotografie: Tomáš Belko, Samuel Vilhan",
        Google_map:
          "https://www.google.com/maps/place/48%C2%B030'32.4%22N+19%C2%B024'21.2%22E/@48.5090296,19.4060288,17z/data=!4m4!3m3!8m2!3d48.508991!4d19.405899?entry=ttu&g_ep=EgoyMDI1MTEzMC4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: "19.405899",
        SIRKA: "48.508991",
        Parcela: "10466/8",
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
    {
      type: "Feature",
      id: 59,
      geometry: {
        type: "Point",
        coordinates: [19.418335, 48.559873],
      },
      properties: {
        FID: 59,
        Nazov: "Kultúrny dom Chudobienec",
        Lokalita: "Partizánska 71, 962 12 Detva",
        TYP: "Sakralne_pam",
        Vznik: "polovica 18. storočia",
        PICURL: "chudobienec.jpg",
        PICURL1: "chudobienec1.jpg",
        PICURL2: "chudobienec2.jpg",
        Text_k:
          "Katolícka cirkev v Detve mala výdavky nielen na kostol a faru,",
        Text: "ale aj na sociálne ustanovizne, ktoré sa nachádzali v jej správe. Karol Anton Medvecký ich nazýva ustanovizne kresťanskej lásky.",
        Text1:
          "Katolícka cirkev v Detve mala výdavky nielen na kostol a faru, ale aj na sociálne ustanovizne, ktoré sa nachádzali v jej správe. Karol Anton Medvecký ich nazýva „ustanovizne kresťanskej lásky“. Medzi ne patril „špitál“, t. j. cirkevný chudobinec, resp. starobinec a o čosi neskôr postavený sirotinec. V roku 1931 dal farár Ján Štrbáň s povolením banskobystrického biskupstva starý špitál zbúrať a na jeho mieste postavili dodnes existujúcu budovu za 130 000,- Kč. Dnes sa veľká sála chudobienca využíva na mestské či cirkevné podujatia, ako sú ochotnícke divadlá, zábavy, karnevaly, akciový predaj tovaru, členské schôdze seniorov z denných centier a základnej organizácie Slovenského zväzu protifašistických bojovníkov, voľby na Slovensku, prednášky, príležitostné výstavy a pod.",
        Zdroj:
          "Fotografie: https://faradetva.sk/o-nas/historia/chudobienec; Text: https://faradetva.sk/o-nas/historia/chudobienec",
        Google_map:
          "https://www.google.com/maps/place/Kult%C3%BArny+dom+Chudobienec/@48.5598912,19.418394,18.55z/data=!4m6!3m5!1s0x47155bc59ef7eea5:0xf6be3ff274e1d4e6!8m2!3d48.5598759!4d19.4183407!16s%2Fg%2F11kh0w1f8s?entry=ttu&g_ep=EgoyMDI1MTIwOS4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: "19.418335",
        SIRKA: "48.559873",
        Parcela: "1394",
        Tel_cislo: " ",
        Mail: " ",
        Stranka: "https://faradetva.sk/o-nas/historia/chudobienec",
      },
    },
    {
      type: "Feature",
      id: 60,
      geometry: {
        type: "Point",
        coordinates: [19.418954, 48.559261],
      },
      properties: {
        FID: 60,
        Nazov: "Rímskokatolícky farský úrad",
        Lokalita: "Partizánska 67, 962 12 Detva",
        TYP: "Sakralne_pam",
        Vznik: 0,
        PICURL: "fara.jpg",
        PICURL1: "fara1.jpg",
        PICURL2: "fara2.jpg",
        Text_k:
          "Podpoľanie je oblasť situovaná na južných a juhovýchodných svahoch najvyššieho sopečného pohoria na Slovensku - Poľany,",
        Text: "územie na rozhraní medzi Slovenským rudohorím a Slovenským stredohorím.",
        Text1:
          "Farská budova v Detve vznikla už v prvej polovici 17. storočia, keď František Péchy daroval kúriu s pozemkami pre potreby fary. V darovanej budove bolo zriadené sídlo farnosti a až do postavenia kostola slúžila aj ako provizórna kaplnka. Pôvodná drevená stavba bola prestavaná na trvalú budovu až v roku 1763, čím sa zabezpečila jej dlhodobá funkcia pre duchovnú správu obce. V priebehu rokov bola budova farského objektu priebežne udržiavaná a po zmene politického režimu v 20. storočí slúžila čiastočne aj na administratívne a spoločenské účely. Dnes farská budova slúži nielen pre duchovnú správu farnosti, ale aj pre rôzne kultúrne a komunitné aktivity, pričom zostáva dôležitou súčasťou histórie a života Detvy.",
        Zdroj:
          "Fotografie: https://www.facebook.com/photo/?fbid=1157841449710204; Text: https://faradetva.sk/o-nas/historia/dejiny-farnosti-detva",
        Google_map:
          "https://www.google.com/maps/place/R%C3%ADmskokatol%C3%ADcky+farsk%C3%BD+%C3%BArad/@48.5592597,19.4179721,19z/data=!4m6!3m5!1s0x47155ada6f69adfb:0xb0ef0231086d24d4!8m2!3d48.5592245!4d19.4191358!16s%2Fg%2F11gzg55_0?entry=ttu&g_ep=EgoyMDI1MTIwOS4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: "19.418954",
        SIRKA: "48.559261",
        Parcela: "2601/1",
        Tel_cislo: "0455455243",
        Mail: "detva@fara.sk",
        Stranka: "https://faradetva.sk/",
      },
    },
    {
      type: "Feature",
      id: 61,
      geometry: {
        type: "Point",
        coordinates: [19.400028, 48.488605],
      },
      properties: {
        FID: 61,
        Nazov: "Božia muka, Detva, Rakytné",
        Lokalita: "Rakytné",
        TYP: "Sakralne_pam",
        Vznik: 0,
        PICURL: "muky_rakytne.jpg",
        Text_k: "",
        Text1: "",
        Zdroj:
          "Fotografie: https://faradetva.sk/o-nas/sakralne-objekty/kaplnky; Text: ",
        Google_map:
          "https://www.google.com/maps/place/48%C2%B029'27.4%22N+19%C2%B023'52.1%22E/@48.4887091,19.3999663,3a,75y,151.55h,82.03t/data=!3m7!1e1!3m5!1sOrdHmw7yMv3wTdyYXl-NQw!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D7.965080949176425%26panoid%3DOrdHmw7yMv3wTdyYXl-NQw%26yaw%3D151.55371479417724!7i16384!8i8192!4m4!3m3!8m2!3d48.490931!4d19.397801?entry=ttu&g_ep=EgoyMDI1MTIwOS4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: "19.400028",
        SIRKA: "48.488605",
        Parcela: "10848",
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
    {
      type: "Feature",
      id: 62,
      geometry: {
        type: "Point",
        coordinates: [19.453787, 48.57716],
      },
      properties: {
        FID: 62,
        Nazov: "Božia muka, Majerovo",
        Lokalita: "Majerovo",
        TYP: "Sakralne_pam",
        Vznik: 0,
        PICURL: "muky_majerovo.jpg",
        Text_k: "",
        Text1: "",
        Zdroj:
          "Fotografie: https://faradetva.sk/o-nas/sakralne-objekty/kaplnky; Text: ",
        Google_map:
          "https://www.google.com/maps/place/48%C2%B035'02.3%22N+19%C2%B027'32.1%22E/@48.5771632,19.4536445,3a,75y,108.84h,84.87t/data=!3m7!1e1!3m5!1sXTUrT29mr2nt3wx3KUx8rA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D5.132615739566276%26panoid%3DXTUrT29mr2nt3wx3KUx8rA%26yaw%3D108.83746536651101!7i16384!8i8192!4m4!3m3!8m2!3d48.583979!4d19.458921?entry=ttu&g_ep=EgoyMDI1MTIwOS4wIKXMDSoASAFQAw%3D%3D",
        DLZKA: "19.453787",
        SIRKA: "48.57716",
        Parcela: "9589",
        Tel_cislo: " ",
        Mail: " ",
        Stranka: " ",
      },
    },
  ],
};
